#!/usr/bin/env python3
#
## @file
# f2f_cherry_pick_humble.py
#
# Copyright (c) 2020 - 2021, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

''' Contains informational and error messages outputted by
the run_command function of for the f2f-cherry-pick command
'''

from colorama import Fore
from colorama import Style

#Error messages for f2f_cherry_pick.py
F2F_CHERRY_PICK_TEMPLATE_AND_FOLDERS = 'argument --template: not allowed with argument --folders'
F2F_CHERRY_PICK_COMMIT_REQUIRED = 'argument Commit: required if --continue and --abort are not specified'
F2F_CHERRY_PICK_NO_TEMPLATE = 'No template defined in the manifest XML matches: {}'
F2F_CHERRY_PICK_NO_REMOTE = 'Remote with name {} does not exist in the manifest XML'
F2F_CHERRY_PICK_NO_ARGUMENTS = 'argument --template, --folders, --continue, --list-templates, and --abort missing: at least one is required'
F2F_CHERRY_PICK_NO_SPARSE = 'Sparse checkout must be disabled to run Folder to Folder Cherry Pick'
F2F_CHERRY_PICK_NO_SPACES = 'Spaces are not allowed in folder names: {}'
F2F_CHERRY_PICK_PATH_NOT_EXIST = '{}{}WARNING:{}{} The path {{}} does not exist at commit {{}} and hence will not be present in the cherry pick{}'.format(Fore.RED, Style.BRIGHT, Style.RESET_ALL, Fore.RED, Style.RESET_ALL)
F2F_CHERRY_PICK_NUM_CHERRY_PICKS_SINGULAR = '{}{}{{}} cherry pick will be needed to complete operation{}'.format(Fore.YELLOW, Style.BRIGHT, Style.RESET_ALL)
F2F_CHERRY_PICK_NUM_CHERRY_PICKS_PLURAL = '{}{}{{}} cherry picks will be needed to complete operation{}'.format(Fore.YELLOW, Style.BRIGHT, Style.RESET_ALL)
F2F_CHERRY_PICK_COMMON_ANCESTOR_REQUIRED = '{} is not in the same branch history as {}, unable to cherry-pick this commit range. To execute this operation use multiple cherry picks'
F2F_CHERRY_PICK_TEMPLATE_COMMIT_MESSAGE = 'Folder to Folder Cherry Pick from {} to {}\n\nCherry Picking the following commits:\n'
F2F_CHERRY_PICK_NON_TEMPLATE_COMMIT_MESSAGE = 'Folder to Folder Cherry Pick\n\nCherry Pick using folder mapping:\n'
F2F_CHERRY_PICK_NON_TEMPLATE_COMMIT_MESSAGE_LINE2 = 'Cherry Picking the following commits:\n'
F2F_CHERRY_PICK_BASH_NOT_FOUND = 'Unable to locate bash.exe'
F2F_CHERRY_PICK_COMMIT_MSG_PY_NOT_FOUND = 'Unable to locate commit_msg.py'
F2F_CHERRY_PICK_GIT_FAILURE = 'Git failed with return code: {}'
F2F_CHERRY_PICK_MERGE_CONFLICT_LINE1 = '{}Merge conflicts have been encountered and must be resolved manually.'.format(Fore.YELLOW)
F2F_CHERRY_PICK_MERGE_CONFLICT_LINE2 = 'Run "git mergetool" to resolve the conflicts.{}'.format(Fore.RESET)
F2F_CHERRY_PICK_MERGE_CONFLICT_LINE3 = 'When you have resolved this problem, run "edkrepo f2f-cherry-pick --continue".'
F2F_CHERRY_PICK_MERGE_CONFLICT_LINE4 = 'To check out the original branch and stop rebasing, run "edkrepo f2f-cherry-pick --abort".'
F2F_CHERRY_PICK_DIRTY_WORKSPACE = 'Workspace is dirty: A clean workspace is required to start a new cherry pick'
F2F_CHERRY_PICK_BRANCH_REQUIRED = 'Workspace is in detached HEAD mode: The destination must be a branch not a commit'
F2F_CHERRY_PICK_SUCCESSFUL = '{}{}Cherry Pick Successful!\n{}It is recommended to run a \"{}{}git clean -df{}\" now, to remove any temporary *.orig files generated by merges.'.format(Fore.GREEN, Style.BRIGHT, Style.RESET_ALL, Fore.CYAN, Style.BRIGHT, Style.RESET_ALL)
F2F_CHERRY_PICK_IN_PROGRESS = 'A Folder to Folder Cherry Pick is already in progress, please abort or continue the existing one before starting a new one'
F2F_CHERRY_PICK_NO_IN_PROGRESS_CONTINUE = 'A Folder to Folder Cherry Pick is not in progress, there is nothing to continue'
F2F_CHERRY_PICK_NO_IN_PROGRESS_ABORT = 'A Folder to Folder Cherry Pick is not in progress, there is nothing to abort'
F2F_CHERRY_PICK_NOT_IN_GIT_REPO = 'The path {} is not within the git repository'
F2F_CHERRY_PICK_CHERRY_PICK_NUM = '{}Cherry Pick #{{}}{}'.format(Fore.MAGENTA, Fore.RESET)
F2F_CHERRY_PICK_CHERRY_PICK_EXCLUDE_LIST = '\tExclude={}'